### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by codeScientist** [google-developer-training/android-basics-kotlin-dessert-clicker-app#10]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#3

**In which task and step of the codelab can this issue be found?**
Step 4

**Describe the problem**
In Use case 1, in step 4, it says: "Notice that none of the DessertClicker logs from the previous activity has been retained."

But I found out that these Logs are retained on logcat. 

Also it says: "Note: The key point here is that onCreate() and onDestroy() are only called once during the lifetime of a single activity instance: onCreate() to initialize the app for the very first time, and onDestroy() to clean up the resources used by your app."

But onCreate and onDestroy were called many times as shown in the screenshot

only the information is reset: desserts sold and price

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![image](https://user-images.githubusercontent.com/8676091/108472341-db28df00-7249-11eb-9d42-9c52c1c35b88.png)

**Comment by jhansitavva** [comment]
@codeScientist 
That is correct, the logs show multiple creation cycles of the activity. 
The activity is being created and destroyed(one lifetime), again created and destroyed (another lifetime).
The reason the data is reinitialized is activity is re-created. 
Hope this helps, please re-open the issue if you. need more clarification
