### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by codeScientist** [google-developer-training/android-basics-kotlin-dessert-clicker-app#11]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

**In which task and step of the codelab can this issue be found?**
Task 5

**Describe the problem**
It says : "Data loss on device rotation", but I tried this and there were no log entries or data loss on device rotation. I tried this using emulator

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jhansitavva** [comment]
@codeScientist 
To observe the logs make sure the emulator or device is selected correctly.
Losing the data means the price will be re-initialized to $0. 

Re-open  the issue it have more questions.
