### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by c-ggr** [google-developer-training/android-basics-kotlin-dessert-clicker-app#12]
**URL of codelab**
https://github.com/google-developer-training/android-basics-kotlin-dessert-clicker-app

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Doesn't work with jdk-15.0.1, only with jdk-13.0.2.
It's important to inform the user,

**Versions**
_Android Studio version:_ 4.1.2

**Comment by jhansitavva** [comment]
@c-ggr 
Thank you for reaching out to us.
Can you share the error you are experiencing on Android Studio please? This app should work with the latest JDK version without any issues.

**Comment by jhansitavva** [comment]
@c-ggr 
Thank you for reaching out to us.
Could you please share the error you are getting in the Android studio. 
This app should work with the latest Android studio version without any issues.
