### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by wasan-m** [google-developer-training/android-basics-kotlin-dessert-clicker-app#15]
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

Wrong on head of content.
![Screen Shot 2564-03-24 at 14 30 15](https://user-images.githubusercontent.com/81288921/112271754-e68a8280-8cad-11eb-9ac8-32b68b353418.png)

**Comment by osuleymanova** [comment]
@wasan-m 
Thank you for reaching out to us. The issue is fixed and published.
