### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by usndangol97** [google-developer-training/android-basics-kotlin-dessert-clicker-app#16]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

**In which task and step of the codelab can this issue be found?**
Explore Configuration Changes

**Describe the problem**
While calling showCurrentDessert() method form onCreate() method when I rotate device's screen it only updates the image.

So I tried calling onDessertClicked() method instead of showCurrentDessert() it both updates the image, Desserts Sold and
the price but it increments the Dessert Sold and price each time I rotate the device screen.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio 4.1.1
_API version of the emulator:_ 
Using the actual device running on android pie

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by amberream** [comment]
It's important where you put the code to restore the instance state.  You must do it right after the line that initializes the binding.  It's important that you also restore the instance state before calling the lines to "Set the TextViews to the right values", so that revenue and amountSold will have the correct values before you set them in the text views.

**Comment by usndangol97** [comment]
> 
> 
> It's important where you put the code to restore the instance state. You must do it right after the line that initializes the binding. It's important that you also restore the instance state before calling the lines to "Set the TextViews to the right values", so that revenue and amountSold will have the correct values before you set them in the text views.

Thank you !
