### ISSUE TITLE
[Codelabs] Android Basics: Activity Lifecycle Keyboard shortcut typo

### ISSUE THREAD

**Issue by v-superuser** [google-developer-training/android-basics-kotlin-dessert-clicker-app#28]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle#2

**In which task and step of the codelab can this issue be found?**
Task 3 - Explore the lifecycle methods and add basic logging
Step 2 > In Android Studio, with MainActivity.kt open and the cursor within the MainActivity class, select Code > Override Methods or press Control+o (Command+o on Mac). A dialog appears with a huge list of all the

**Describe the problem**
In the mentioned step it mentions that the "Override Methods" can be opened via Command+O on Mac but the shortcut is Control+O on Mac as well.
<img width="1440" alt="Screenshot 2021-06-22 at 2 15 38 PM" src="https://user-images.githubusercontent.com/4995273/122893959-68994e80-d364-11eb-960a-b0020013ae08.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  Android Studio 4.2.1
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@v-superuser 
Thank you for reaching out to us. 
Both variants Ctrl+O and Command+O are correct. It depends upon the "System Preferences" settings. By default Command Key is set up. 
You may switch between the Control and Command Keys in macOS following the below steps:
Open “System Preferences” from the Launchpad.
Click on the Keyboard option.
Click the “Modifier Keys…” button at the bottom-right.
In the “Control (^) Key” field, change it to “Command.” And in the “Command Key” field, change it to “Control.” Click OK.
