### ISSUE TITLE
Android Basics: DAC rendering issue - Activity Lifecycle

### ISSUE THREAD

**Issue by adalius** [google-developer-training/android-basics-kotlin-dessert-clicker-app#4]
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

Step 5

Website is missing a line break before '5.' so it is at the end of the last paragraph of step 4.

**Comment by jhansitavva** [comment]
@adalius 
Do you mean image rendering issue?
![image](https://user-images.githubusercontent.com/24260141/103710731-a1866800-4f6a-11eb-95ed-094077149d2a.png)

**Comment by adalius** [comment]
No. This. 
<img width="739" alt="gitpic" src="https://user-images.githubusercontent.com/6215738/103713550-3e083480-4f82-11eb-98fb-65040ea0fb26.png">

**Comment by osuleymanova** [comment]
@adalius 
Thank you for reaching out to us. The issue is fixed and published.
