### ISSUE TITLE
Android Basics: Activity Lifecycle / problem with onDestroy()

### ISSUE THREAD

**Issue by diskostu** [google-developer-training/android-basics-kotlin-dessert-clicker-app#40]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle

**In which task and step of the codelab can this issue be found?**
3 (Explore the lifecycle methods and add basic logging)

**Describe the problem**
When overriding `onDestroy()`, the call to `super.onDestroy()` has to be at the very end of the method; otherwise, we don't see any logging.
So, the correct code would be:
```kotlin
    override fun onDestroy() {
        Log.d(TAG_LIFECYCLE, "onDestroy called")
        
        super.onDestroy()
    }
```

**Steps to reproduce?**
1. Implement `onDestroy()` as stated in the codelab
2. Run the app
3. Close the app via the Recents menu
2. No logging for `onDestroy()` can be found in Logcat

**Versions**
_Android Studio version:_ Android Studio Bumblebee | 2021.1.1 RC 1
_API version of the emulator:_ tested on a physical device (Pixel 5, Android 12)

**Comment by cheng-dai** [comment]
The original code works for me. But when closing the app using the back button didn't give me the destroy log. Closing from the recent apps screen works. Tested on an Android 12 Xiaomi device.

**Comment by krishan-here** [comment]
while pressing back button, I don't see any destroy log.
