### ISSUE TITLE
Android Basics: Activity Lifecycle - no onStart() listed in Override Memebers list

### ISSUE THREAD

**Issue by tamarabuilds** [google-developer-training/android-basics-kotlin-dessert-clicker-app#42]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle&hl=en#2

**In which task and step of the codelab can this issue be found?**
Step 2: Implement the onStart() method > Step 1. 

**Describe the problem**
While the steps suggest we open the Override Members screen and find the onStart() member, I cannot find it in the list.

**Versions**
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 16, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), org.intellij.plugins.markdown (211.7142.37)

**Additional information**
![image](https://user-images.githubusercontent.com/98510821/156468517-846bffda-d82b-4cf5-88af-75d3fc3caa4a.png)

**Comment by shepardsn** [comment]
I ran into the same problem but discovered it is there. It is a method on the AppCompatActivity, not Activity.  If you search for it by typing 'onStart', you need to down-arrow several times to find the method on AppCompatActivity.
