### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by Wavey1287** [google-developer-training/android-basics-kotlin-dessert-clicker-app#48]
[**URL of codelab**](https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#2)

3 Step2.1 onStart()

onStart isn't in the list of override members.   Has been deprecated.  You should probably update this with the replacement.

**Comment by vexijio** [comment]
How come onStart() is deprecated? Maybe you picked the wrong member?
