### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by amaljoe** [google-developer-training/android-basics-kotlin-dessert-clicker-app#5]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#1

**In which task and step of the codelab can this issue be found?**
Task: Stages of the activity lifecycle
Step: 2) App overview

**Describe the problem**
The starter code given is actually the completed code.

**Comment by jhansitavva** [comment]
@amaljoe 
Thank you so much for reaching out to us.
There are two branches in the repo, starter and main. 
The starter branch contains the starter code and main brach contains the solution code. 
Please make sure to select **starter** branch before downloading the source code. 

![image](https://user-images.githubusercontent.com/24260141/106807550-245c1a80-661e-11eb-801e-fd8d46d697db.png)
