### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by amber-pan** [google-developer-training/android-basics-kotlin-dessert-clicker-app#53]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#4

**In which task and step of the codelab can this issue be found?**
7. In onCreate(), in the block that restores the state from the bundle, call showCurrentDessert()

**Describe the problem**
if call showCurrentDessert() in onCreate(), app will crash when change orientation. the correct place to add this line of code should be onStart(), or onResume()

**Steps to reproduce?**
1. Go to... Dessert Clicker app, tap on the dessert at least 5 times so the dessert image change
2. Click on... click on the orientation from configuration tools on the emulator
3. See error... app crashes

**Versions**
_Android Studio version:_ Bumblebee
_API version of the emulator:_ API 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by deepanshu0304** [comment]
same error happens with me also
