### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by NGBarai** [google-developer-training/android-basics-kotlin-dessert-clicker-app#64]
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#0

[1. Welcome](https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#0)

It seems little difficult to understand the meaning of the following sentence even after reading 2-3 times:
"As a user navigates between activities in your app (and into and out of your app), those activities **each transition between different states in the activity lifecycle**."

As a reference, I am mentioning that, I have scored 8 in IELTS Reading, and I read English everyday.
Version: Last updated Jan 29, 2022

I believe, like other sentences, more clarity is possible to achieve in the above mentioned sentence.
Thank you.

**Comment by kalsangdorjee** [comment]
As we know an activity is simply a screen, like a login screen in an app. And in an app, there are more than one screen. Users go through these screens back and forth while using an app. e.g. login screen --> new feeds. So it is safe to say that they navigate between activities in an app. 

Users can also navigate to screens of other apps, which means activities of other apps. For an example, when you click on an URL sent by a friend of yours in Messenger, a web browser opens to handle the URL. Messenger and web browser are two different apps and you navigate from an activity or screen of Messenger to a activity or screen of the web browser. 

When users navigates back and forth between activities, different activity lifecycle methods are called in respective activities.
