### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by JETFIRE206** [google-developer-training/android-basics-kotlin-dessert-clicker-app#65]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-activity-lifecycle#2

**In which task and step of the codelab can this issue be found?**
Under "**Stages of the activity lifecycle**" => "**Explore the lifecycle methods and add basic logging**" => "**Step 1: Examine the onCreate() method and add logging**" => "**6. In the Logcat window, type D/MainActivity into the search field.**"

**Describe the problem**
Given **Logcat** has changed ([New Logcat](https://developer.android.com/studio/releases#logcat)), the instructions on using Logcat are _out-of-date_ and no longer work. 

**Steps to reproduce?**
1. Follow the Code Lab and attempt to perform step "**6. In the Logcat window, type D/MainActivity into the search field.**"

**Versions**
Android Studio Dolphin | 2021.3.1 Patch 1

**Additional information**
Here's the filter command I used to see the expected output
![image](https://user-images.githubusercontent.com/12277657/205710974-bd65ad6e-c098-4796-ae6c-cbf837d32f1d.png)

**Comment by kalsangdorjee** [comment]
Yes indeed the logcat has been updated and it comes with new ways of filtering logs. The old filtering mechanism doesn't work with the new logcat and you need to follow the filtering rule specified [here ](https://developer.android.com/studio/releases#logcat-search) in order to filter logs using new logcat.
