### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by Bk8lst** [google-developer-training/android-basics-kotlin-dessert-clicker-app#70]
**URL of codelab**
https://github.com/google-developer-training/android-basics-kotlin-dessert-clicker-app/issues/new?&title=Android%20Basics%3A%20Activity%20Lifecycle

**In which task and step of the codelab can this issue be found?**
Explore configuration changes

**Describe the problem**
App does not support rotating screen. Stays in protrait mode.

**Steps to reproduce?**
1. Go to... 
2. override fun onSaveInstanceState(outState: Bundle) {
   super.onSaveInstanceState(outState)

   Log.d(TAG, "onSaveInstanceState Called")
}
Run the app

3. Click on... cupcake a few times

4. Rotate the device (emulator, Pixel 6 API 30)
5. Nothing happens

**Versions**
_Android Studio version:_  Electric Eel|2022.1.1
Build #AI-221.6008.13.2211.9477386, built on January 10, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
_API version of the emulator:_ (emulator, Pixel 6 API 30)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot (6)](https://user-images.githubusercontent.com/35199090/214659930-a5266c15-150d-4620-905d-c3e3004cad3f.png)

**Comment by StephanVanBiljon** [comment]
Turn auto-rotate on in the device display settings
