### ISSUE TITLE
Android Basics: Activity Lifecycle

### ISSUE THREAD

**Issue by nivivier** [google-developer-training/android-basics-kotlin-dessert-clicker-app#8]
**URL of codelab**
https://developer.android.com/courses/quizzes/android-basics-kotlin-unit-3-pathway-1/android-basics-kotlin-unit-3-pathway-1?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-1%23quiz-%2Fcourses%2Fquizzes%2Fandroid-basics-kotlin-unit-3-pathway-1%2Fandroid-basics-kotlin-unit-3-pathway-1

**In which task and step of the codelab can this issue be found?**

In the question #2 :
```
Given the following code, what is the result of oneWordCities[1]?
val cities = listOf(“Jeddah”, “Bengaluru” “Shenzhen”, “Abu Dhabi”, “Mountain View”, “Tripoli”, “Bengaluru”, “Lima”, “Mandalay”, “Tripoli”)
val oneWordCities = cities.toSet().toList().filter { !it.contains(“ “)}.sorted()
```

**Describe the problem**
- comma missing between “Bengaluru” and “Shenzhen”,
- **“** and **”** (typographic quotation marks) characters) should be neutral quotation marks : **"** 

**Steps to reproduce?**
1. Go to the quizz
2. View the question number 2
3. See error in the sample code of the question

**Comment by jhansitavva** [comment]
@nivivier 
Thank you so much for reporting this issue. This is fixed and will be published soon.

**Comment by nivivier** [comment]
Great! Thanks!
